# Generated by Django 2.2.18 on 2021-02-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, db_column='cover', max_length=255, null=True, upload_to='cars', verbose_name='Обложка'),
        ),
    ]
